version: x.x.{build}
branches:
  only:
  - master
image: Visual Studio 2015
configuration: Release
install:
- cmd: git submodule update --init --recursive
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: appveyor-retry nuget restore
build:
  project: dnSpy.sln
  parallel: true
  verbosity: normal
artifacts:
- path: dnSpy/dnSpy/bin/Release
  name: dnSpy