name: GitHub CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types: released

env:
  CI_REQ_DOTNET_SDK_VER: 5.0.100

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{env.CI_REQ_DOTNET_SDK_VER}}

      # Build each tfm separately since building all requires too much disk space
      - name: Build dnSpy (.NET Framework)
        shell: pwsh
        run: |
          $msbuildPath = Split-Path (& "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -requires Microsoft.Component.MSBuild -find MSBuild\Current\Bin\amd64\MSBuild.exe | Select-Object -First 1) -Parent
          $env:PATH = $msbuildPath + ';' + $env:PATH
          .\build.ps1 netframework
          New-Item -ItemType Directory -Path C:\builtfiles -Force > $null
          Compress-Archive -Path dnSpy\dnSpy\bin\Release\net48\* -DestinationPath C:\builtfiles\dnSpy-netframework.zip
          .\clean-all.cmd

      - name: Build dnSpy (.NET x86)
        shell: pwsh
        run: |
          $msbuildPath = Split-Path (& "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -requires Microsoft.Component.MSBuild -find MSBuild\Current\Bin\amd64\MSBuild.exe | Select-Object -First 1) -Parent
          $env:PATH = $msbuildPath + ';' + $env:PATH
          .\build.ps1 net-x86
          New-Item -ItemType Directory -Path C:\builtfiles -Force > $null
          Compress-Archive -Path dnSpy\dnSpy\bin\Release\net5.0-windows\win-x86\publish\* -DestinationPath C:\builtfiles\dnSpy-net-win32.zip
          .\clean-all.cmd

      - name: Build dnSpy (.NET x64)
        shell: pwsh
        run: |
          $msbuildPath = Split-Path (& "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -requires Microsoft.Component.MSBuild -find MSBuild\Current\Bin\amd64\MSBuild.exe | Select-Object -First 1) -Parent
          $env:PATH = $msbuildPath + ';' + $env:PATH
          .\build.ps1 net-x64
          New-Item -ItemType Directory -Path C:\builtfiles -Force > $null
          Compress-Archive -Path dnSpy\dnSpy\bin\Release\net5.0-windows\win-x64\publish\* -DestinationPath C:\builtfiles\dnSpy-net-win64.zip
          .\clean-all.cmd

      - uses: actions/upload-artifact@v2
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
        with:
          name: dnSpy-netframework
          path: C:\builtfiles\dnSpy-netframework.zip
          if-no-files-found: error

      - uses: actions/upload-artifact@v2
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
        with:
          name: dnSpy-net-win32
          path: C:\builtfiles\dnSpy-net-win32.zip
          if-no-files-found: error

      - uses: actions/upload-artifact@v2
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
        with:
          name: dnSpy-net-win64
          path: C:\builtfiles\dnSpy-net-win64.zip
          if-no-files-found: error

      # Create a new release: create a tag, then 'git push origin <tagname>', wait for it to build
      - name: Create a new GitHub release if a new tag is pushed
        uses: softprops/action-gh-release@b28d815 #@v1
        with:
          files: |
            C:\builtfiles\dnSpy-netframework.zip
            C:\builtfiles\dnSpy-net-win32.zip
            C:\builtfiles\dnSpy-net-win64.zip
          body: |
            If your antivirus software complains, it's a false positive and you should contact them. I can't fix their buggy software.
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
